<!doctype HTML public "-//W3C//DTD HTML 4.0 Frameset//EN">

<html>

<head>
<title>Extrusion</title>
<meta http-equiv="content-type" content="text/html; charset=windows-1252">
<meta name="generator" content="RoboHelp by eHelp Corporation www.ehelp.com">
<link rel="stylesheet" href="default_ns.css"><script type="text/javascript" language="JavaScript" title="WebHelpSplitCss">
<!--
if (navigator.appName !="Netscape")
{   document.write("<link rel='stylesheet' href='default.css'>");}
//-->
</script>
<style type="text/css">
<!--
img_whs1 { width:20px; height:20px; border-style:none; }
p.whs2 { font-size:12pt; }
p.whs3 { font-size:12pt; margin-left:40px; }
img_whs4 { border:none; width:312px; height:350px; float:none; border-style:none; }
p.whs5 { font-size:12pt; font-weight:bold; }
p.whs6 { font-size:12pt; font-style:italic; margin-left:40px; }
img_whs7 { border:none; float:none; width:300px; height:175px; border-style:none; }
img_whs8 { border:none; width:350px; height:175px; float:none; border-style:none; }
-->
</style><script type="text/javascript" language="JavaScript" title="WebHelpInlineScript">
<!--
function reDo() {
  if (innerWidth != origWidth || innerHeight != origHeight)
     location.reload();
}
if ((parseInt(navigator.appVersion) == 4) && (navigator.appName == "Netscape")) {
	origWidth = innerWidth;
	origHeight = innerHeight;
	onresize = reDo;
}
onerror = null; 
//-->
</script>
<style type="text/css">
<!--
div.WebHelpPopupMenu { position:absolute; left:0px; top:0px; z-index:4; visibility:hidden; }
-->
</style><script type="text/javascript" language="javascript1.2" src="whmsg.js"></script>
<script type="text/javascript" language="javascript" src="whver.js"></script>
<script type="text/javascript" language="javascript1.2" src="whproxy.js"></script>
<script type="text/javascript" language="javascript1.2" src="whutils.js"></script>
<script type="text/javascript" language="javascript1.2" src="whtopic.js"></script>
</head>
<body><script type="text/javascript" language="javascript1.2">
<!--
if (window.gbWhTopic)
{
	if (window.addTocInfo)
	{
	addTocInfo("Geometry module\nCreating geometrical objects\nCreating Complex Objects\nExtrusion");
addButton("show",BTN_TEXT,"Show","","","","",0,0,"","","");

	}
	if (window.writeBtnStyle)
		writeBtnStyle();

	if (window.writeIntopicBar)
		writeIntopicBar(1);

	if (window.setRelStartPage)
	{
	setRelStartPage("geom.htm");

		autoSync(1);
		sendSyncInfo();
		sendAveInfoOut();
	}
}
else
	if (window.gbIE4)
		document.location.reload();
//-->
</script>
<h1><span style="font-size: 14pt;"><font size=4 style="font-size:14pt;"><b style="font-weight: bold;"><img src="files/salome2_sp3_generationgui_functions_salome2_sp3_generationgui_functions_image56.gif" width="20px" height="20px" border="0" class="img_whs1"> &nbsp;</b></font></span>Extrusion</h1>

<p><b><span style="font-weight: normal;">T</b>o</span> generate an <span 
 style="font-weight: bold;"><B>Extrusion</B></span> on an object in the <span 
 style="font-weight: bold;"><B>Main Menu</B></span> select <span style="font-weight: bold;"><B>New 
 Entity - &gt; Generation &nbsp;- 
 &gt; Extrusion</B></span></p>

<p class="whs2">&nbsp;</p>

<p class="whs2">To create an Extrusion (Prism) you should define 
 the <span style="font-weight: bold;"><B>Base Shape </B></span>(a basis of the 
 extrusion)<span style="font-weight: bold;"><B>, </B></span>the <span style="font-weight: bold;"><B>Vector</B></span> 
 (a direction of the extrusion) and the <span style="font-weight: bold;"><B>Height</B></span> 
 of extrusion. &nbsp;</p>

<p class="whs2"><b style="font-weight: bold;"><span style="font-weight: normal;">The</span> 
 Result <span style="font-weight: normal;">of the operation will be a</span></b> 
 GEOM_Object (edge, face, solid or compsolid).</p>

<p class="whs2"><span style="font-weight: bold;"><B><b style="font-weight: bold;">TUI 
 Command :</b><i> </i></B></span><span style="font-style: italic;"><I>geompy.MakePrismVecH(Base, 
 Vector, Height)</I></span></p>

<p class="whs2"><span style="font-size: 12pt;"><font size=3 style="font-size:12pt;"><b style="font-weight: bold;">Arguments:</b> 
 Name + 1 shape (vertex, edge, wire, face or shell) serving as base object 
 + 1 vector (for direction of the extrusion) + 1 value (dimension).</font></span></p>

<p>&nbsp;</p>

<p class="whs3"><img src="pics/extrusion.png" x-maintain-ratio="TRUE" width="312px" height="350px" border="0" class="img_whs4"></p>

<p class="whs2">&nbsp;</p>

<p class="whs5">NB! <span style="font-weight: normal;">The 
 is another way to create an</span> Extrusion, <span style="font-weight: normal;">which 
 is currently accessible only via</span> TUI commands.</p>

<p class="whs5"><span style="font-weight: normal;">You 
 can define the</span> Extrusion <span style="font-weight: normal;">by 
 the </span>Base Shape<span style="font-weight: normal;"> and the </span>Start<span 
 style="font-weight: normal;"> and </span>End Point<span style="font-weight: normal;"> 
 of the </span>Vector<span style="font-weight: normal;"> &nbsp;(in 
 this way you don't need to create it in advance).</span> </p>

<p class="whs5"><b style="font-weight: bold;">TUI 
 Command:</b> <span style="font-weight: normal; font-style: italic;"><I>geompy.MakePrism(Base, 
 Point1, Point2) </I></span></p>

<p>&nbsp;</p>

<p class="whs3">&nbsp;</p>

<p class="whs2"><b style="font-weight: bold;">Examples:</b></p>

<p class="whs2">&nbsp;</p>

<p class="whs6">Base Shape &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Prisms</p>

<p class="whs3"><img src="pics/prisms_basessn.png" x-maintain-ratio="TRUE" width="300px" height="175px" border="0" class="img_whs7"> <img src="pics/prismssn.png" x-maintain-ratio="TRUE" width="350px" height="175px" border="0" class="img_whs8"> &nbsp;</p>

<p class="whs2">&nbsp;</p>

<p class="whs2">Our <span style="font-weight: bold;"><B>TUI Scripts</B></span> 
 provide you with useful examples of creation of <a href="complex_objects.htm#bookmark">Complex 
 Geometric Objects</a>. </p>

<p>&nbsp;</p>

<script type="text/javascript" language="javascript1.2">
<!--
if (window.writeIntopicBar)
	writeIntopicBar(0);
//-->
</script>
</body>
</html>
