<!doctype HTML public "-//W3C//DTD HTML 4.0 Frameset//EN">

<html>

<head>
<title>Face</title>
<meta http-equiv="content-type" content="text/html; charset=windows-1252">
<meta name="generator" content="RoboHelp by eHelp Corporation www.ehelp.com">
<link rel="stylesheet" href="default_ns.css"><script type="text/javascript" language="JavaScript" title="WebHelpSplitCss">
<!--
if (navigator.appName !="Netscape")
{   document.write("<link rel='stylesheet' href='default.css'>");}
//-->
</script>
<style type="text/css">
<!--
img_whs1 { width:20px; height:20px; border-style:none; }
p.whs2 { font-size:12pt; }
p.whs3 { font-size:12pt; margin-left:40px; }
img_whs4 { border:none; width:400px; height:315px; float:none; }
img_whs5 { border:none; width:180px; height:180px; float:none; border-style:none; }
img_whs6 { border:none; float:none; width:180px; height:180px; border-style:none; }
-->
</style><script type="text/javascript" language="JavaScript" title="WebHelpInlineScript">
<!--
function reDo() {
  if (innerWidth != origWidth || innerHeight != origHeight)
     location.reload();
}
if ((parseInt(navigator.appVersion) == 4) && (navigator.appName == "Netscape")) {
	origWidth = innerWidth;
	origHeight = innerHeight;
	onresize = reDo;
}
onerror = null; 
//-->
</script>
<style type="text/css">
<!--
div.WebHelpPopupMenu { position:absolute; left:0px; top:0px; z-index:4; visibility:hidden; }
p.WebHelpNavBar { text-align:right; }
-->
</style><script type="text/javascript" language="javascript1.2" src="whmsg.js"></script>
<script type="text/javascript" language="javascript" src="whver.js"></script>
<script type="text/javascript" language="javascript1.2" src="whproxy.js"></script>
<script type="text/javascript" language="javascript1.2" src="whutils.js"></script>
<script type="text/javascript" language="javascript1.2" src="whtopic.js"></script>
<script type="text/javascript" language="javascript1.2">
<!--
if (window.gbWhTopic)
{
	if (window.setRelStartPage)
	{
	addTocInfo("Geometry module\nCreating geometrical objects\nCreating Advanced Geometrical Objects\nFace");
addButton("show",BTN_IMG,"Show","","","","",0,0,"whd_show0.gif","whd_show2.gif","whd_show1.gif");
addButton("hide",BTN_IMG,"Hide","","","","",0,0,"whd_hide0.gif","whd_hide2.gif","whd_hide1.gif");

	}


	if (window.setRelStartPage)
	{
	setRelStartPage("index.htm");

		autoSync(1);
		sendSyncInfo();
		sendAveInfoOut();
	}

}
else
	if (window.gbIE4)
		document.location.reload();
//-->
</script>
</head>
<body><script type="text/javascript" language="javascript1.2">
<!--
if (window.writeIntopicBar)
	writeIntopicBar(4);
//-->
</script>
<h1><span style="font-size: 14pt;"><font size=4 style="font-size:14pt;"><img src="salome2_sp3_buildgui_functions_salome2_sp3_buildgui_functions_image16.gif" width="20px" height="20px" border="0" class="img_whs1"> &nbsp;</font></span>Face</h1>

<p class="whs2"><b style="font-weight: normal;">T</b>o create 
 a <span style="font-weight: bold;"><B>Face</B></span> in the Main Menu select 
 <span style="font-weight: bold;"><B>New Entity - &gt; Build - &gt; Face</B></span></p>

<p class="whs2">&nbsp;</p>

<p class="whs2"><b style="font-weight: bold;"><span style="font-weight: normal;">To 
 create a </span><span style="font-weight: bold;"><B>Face</B></span><span style="font-weight: normal;"> 
 you need to select input shape(s). </span></b>The list of input shapes 
 can include shapes of any type; if the shapes are not wires or edges, 
 the algorithm extracts all edges from the input shapes and works on the 
 obtained edges. </p>

<p class="whs2">The edges and wires do not necessary have to 
 be closed, the algorithm automatically builds a wire of maximum length 
 from all given edges and wires. If it founds multiple closed wires, it 
 can build a face with holes or some separate faces, depending on the placement 
 of the wires. If some resulting wires remain open, they will be added 
 in the resulting compound as is. </p>

<p class="whs2">&nbsp;</p>

<p class="whs2"><b style="font-weight: bold;"><span style="font-weight: normal;">Check 
 </span><span style="font-weight: bold;"><B>Try to create a planar face</B></span><span 
 style="font-weight: normal;"> to create a planar face or nothing if it 
 is impossible.</span></b></p>

<p class="whs2"><b style="font-weight: bold;"><span style="font-weight: normal;">The</span> 
 Result<span style="font-weight: normal;"> will be a</span></b> GEOM_Object 
 (FACE).</p>

<p class="whs2">&nbsp;</p>

<p class="whs2"><b style="font-weight: bold;">TUI Command:</b><i> 
 </i><span style="font-style: italic;"><I>geompy.MakeFaceWires([list of shapes], 
 isPlanarWanted</I></span>)</p>

<p class="whs2"><b style="font-weight: bold;">Arguments:</b> 
 Name + 1 wire.</p>

<p class="whs2">&nbsp;</p>

<p class="whs3"><img src="pics/neo-obj4.png" x-maintain-ratio="TRUE" width="400px" height="315px" border="0" class="img_whs4"></p>

<p class="whs2">&nbsp;</p>

<p class="whs2">&nbsp;</p>

<p class="whs2"><b style="font-weight: bold;">Example:</b></p>

<p class="whs2">&nbsp;</p>

<p class="whs3"><img src="pics/facesn1.png" x-maintain-ratio="TRUE" width="180px" height="180px" border="0" class="img_whs5"> <img src="pics/facesn2.png" x-maintain-ratio="TRUE" width="180px" height="180px" border="0" class="img_whs5"> <img src="pics/facesn3.png" x-maintain-ratio="TRUE" width="180px" height="180px" border="0" class="img_whs6"></p>

<p class="whs3">&nbsp;</p>

<p class="whs2">Our TUI Scripts provide you with useful examples 
 of creation of <a href="geometrical_objects.htm#bookmark1">Advanced Geometric 
 Objects</a>. </p>

<p>&nbsp;</p>

<script type="text/javascript" language="javascript1.2">
<!--
if (window.writeIntopicBar)
	writeIntopicBar(0);
//-->
</script>
</body>
</html>
