<!doctype HTML public "-//W3C//DTD HTML 4.0 Frameset//EN">

<html>

<head>
<title>Geometrical Objects</title>
<meta http-equiv="content-type" content="text/html; charset=windows-1252">
<meta name="generator" content="RoboHelp by eHelp Corporation www.ehelp.com">
<link rel="stylesheet" href="default_ns.css"><script type="text/javascript" language="JavaScript" title="WebHelpSplitCss">
<!--
if (navigator.appName !="Netscape")
{   document.write("<link rel='stylesheet' href='default.css'>");}
//-->
</script>
<style type="text/css">
<!--
p.whs1 { font-family:'Lucida Console' , monospace; }
p.whs2 { font-family:'Times New Roman' , serif; }
-->
</style><script type="text/javascript" language="JavaScript" title="WebHelpInlineScript">
<!--
function reDo() {
  if (innerWidth != origWidth || innerHeight != origHeight)
     location.reload();
}
if ((parseInt(navigator.appVersion) == 4) && (navigator.appName == "Netscape")) {
	origWidth = innerWidth;
	origHeight = innerHeight;
	onresize = reDo;
}
onerror = null; 
//-->
</script>
<style type="text/css">
<!--
div.WebHelpPopupMenu { position:absolute; left:0px; top:0px; z-index:4; visibility:hidden; }
p.WebHelpNavBar { text-align:right; }
-->
</style><script type="text/javascript" language="javascript1.2" src="whmsg.js"></script>
<script type="text/javascript" language="javascript" src="whver.js"></script>
<script type="text/javascript" language="javascript1.2" src="whproxy.js"></script>
<script type="text/javascript" language="javascript1.2" src="whutils.js"></script>
<script type="text/javascript" language="javascript1.2" src="whtopic.js"></script>
<script type="text/javascript" language="javascript1.2">
<!--
if (window.gbWhTopic)
{
	if (window.setRelStartPage)
	{
	addTocInfo("Geometry module\nTUI Scripts\nCreating Geometric Objects\nAdvanced Geometrical Objects");
addButton("show",BTN_IMG,"Show","","","","",0,0,"whd_show0.gif","whd_show2.gif","whd_show1.gif");
addButton("hide",BTN_IMG,"Hide","","","","",0,0,"whd_hide0.gif","whd_hide2.gif","whd_hide1.gif");

	}


	if (window.setRelStartPage)
	{
	setRelStartPage("index.htm");

		autoSync(1);
		sendSyncInfo();
		sendAveInfoOut();
	}

}
else
	if (window.gbIE4)
		document.location.reload();
//-->
</script>
</head>
<body><script type="text/javascript" language="javascript1.2">
<!--
if (window.writeIntopicBar)
	writeIntopicBar(4);
//-->
</script>
<h1>Advanced Geometrical Objects</h1>

<h3><a name=bookmark>Creation of an Edge</a></h3>

<p class="whs1">import geompy</p>

<p class="whs1">import salome</p>

<p class="whs1">gg = salome.ImportComponentGUI(&quot;GEOM&quot;)</p>

<p>&nbsp;</p>

<p># create vertices</p>

<p class="whs1">p0 &nbsp;&nbsp;= 
 geompy.MakeVertex(0. &nbsp;, 
 0. &nbsp;, 0. 
 &nbsp;)</p>

<p class="whs1">pxyz = geompy.MakeVertex(100., 
 100., 100.)</p>

<p>&nbsp;</p>

<p># create an edge</p>

<p class="whs1">edge = geompy.MakeEdge(p0, 
 pxyz)</p>

<p>&nbsp;</p>

<p># add object in the study</p>

<p class="whs1">id_edge = geompy.addToStudy(edge,&quot;Edge&quot;)</p>

<p>&nbsp;</p>

<p># display an edge</p>

<p class="whs1">gg.createAndDisplayGO(id_edge) 
 </p>

<p class="whs1">&nbsp;</p>

<h3><a name=Creation>Creation of a Wire</a></h3>

<p class="whs1"><span style="font-family: 'Lucida Console', monospace;">import 
 geompy</span></p>

<p class="whs1">import salome</p>

<p class="whs1">gg = salome.ImportComponentGUI(&quot;GEOM&quot;)</p>

<p class="whs2">&nbsp;</p>

<p class="whs2"># create vertices</p>

<p class="whs1">px &nbsp;&nbsp;= 
 geompy.MakeVertex(100., 0. &nbsp;, 
 0. &nbsp;)</p>

<p class="whs1">py &nbsp;&nbsp;= 
 geompy.MakeVertex(0. &nbsp;, 
 100., 0. &nbsp;)</p>

<p class="whs1">pz &nbsp;&nbsp;= 
 geompy.MakeVertex(0. &nbsp;, 
 0. &nbsp;, 100.)</p>

<p class="whs2">&nbsp;</p>

<p class="whs2"># create a vector from 
 two points</p>

<p class="whs1">vxy = geompy.MakeVector(px, 
 py)</p>

<p class="whs1">&nbsp;</p>

<p class="whs2"># create an arc from 
 three points</p>

<p class="whs1">arc = geompy.MakeArc(py, 
 pz, px)</p>

<p class="whs2">&nbsp;</p>

<p class="whs2"># create a wire</p>

<p class="whs1">wire = geompy.MakeWire([vxy, 
 arc])</p>

<p class="whs2">&nbsp;</p>

<p class="whs2"># add an object in the 
 study</p>

<p class="whs1">id_wire = geompy.addToStudy(wire,&quot;Wire&quot;)</p>

<p class="whs2">&nbsp;</p>

<p class="whs2"># display the wire</p>

<p class="whs1">gg.createAndDisplayGO(id_wire) 
 </p>

<p class="whs1">&nbsp;</p>

<h3><a name=bookmark1>Creation of a Face</a></h3>

<p class="whs1"><span style="font-family: 'Lucida Console', monospace;">import 
 salome</span></p>

<p class="whs1">salome.salome_init()</p>

<p class="whs1">&nbsp;</p>

<p class="whs1">import geompy</p>

<p class="whs1">geompy.init_geom(salome.myStudy)</p>

<p class="whs1">&nbsp;</p>

<p class="whs1">Box_1 = geompy.MakeBoxDXDYDZ(200, 
 200, 200)</p>

<p class="whs1">geompy.addToStudy(Box_1, 
 &quot;Box_1&quot;)</p>

<p class="whs1">&nbsp;</p>

<p class="whs1">edges = geompy.SubShapeAllSorted(Box_1, 
 geompy.ShapeType[&quot;EDGE&quot;])</p>

<p class="whs1">&nbsp;</p>

<p class="whs1">Edge_1 = edges[0]</p>

<p class="whs1">Edge_2 = edges[4]</p>

<p class="whs1">Edge_3 = edges[5]</p>

<p class="whs1">Edge_4 = edges[8]</p>

<p class="whs1">Edge_5 = edges[9]</p>

<p class="whs1">&nbsp;</p>

<p class="whs1">geompy.addToStudyInFather(Box_1, 
 Edge_1, &quot;Edge_1&quot;)</p>

<p class="whs1">geompy.addToStudyInFather(Box_1, 
 Edge_2, &quot;Edge_2&quot;)</p>

<p class="whs1">geompy.addToStudyInFather(Box_1, 
 Edge_3, &quot;Edge_3&quot;)</p>

<p class="whs1">geompy.addToStudyInFather(Box_1, 
 Edge_4, &quot;Edge_4&quot;)</p>

<p class="whs1">geompy.addToStudyInFather(Box_1, 
 Edge_5, &quot;Edge_5&quot;)</p>

<p class="whs1">&nbsp;</p>

<p class="whs1">Wire_1 = geompy.MakeWire([Edge_1, 
 Edge_2])</p>

<p class="whs1">geompy.addToStudy(Wire_1, 
 &quot;Wire_1&quot;)</p>

<p class="whs1">&nbsp;</p>

<p class="whs1">Comp_1 = geompy.MakeCompound([Wire_1, 
 Edge_3, Edge_4])</p>

<p class="whs1">geompy.addToStudy(Comp_1, 
 &quot;Compound_1&quot;)</p>

<p class="whs1">&nbsp;</p>

<p class="whs1">salome.sg.updateObjBrowser(1)</p>

<p class="whs1">&nbsp;</p>

<p class="whs1">Face_1 = geompy.MakeFaceWires([Comp_1], 
 True)</p>

<p class="whs1">geompy.addToStudy(Face_1, 
 &quot;Face_1&quot;)</p>

<p class="whs1">&nbsp;</p>

<p class="whs1">Face_2 = geompy.MakeFaceWires([Wire_1, 
 Edge_3, Edge_4], True)</p>

<p class="whs1">geompy.addToStudy(Face_2, 
 &quot;Face_2&quot;)</p>

<p class="whs1">&nbsp;</p>

<p class="whs1">Vertex_1 = geompy.MakeVertex(0, 
 0, 0)</p>

<p class="whs1">Vertex_2 = geompy.MakeVertex(0, 
 210, 0)</p>

<p class="whs1">Vertex_3 = geompy.MakeVertex(100, 
 210, 0)</p>

<p class="whs1">Vertex_4 = geompy.MakeVertex(100, 
 0, 0)</p>

<p class="whs1">Vertex_5 = geompy.MakeVertex(140, 
 105, 0)</p>

<p class="whs1">Vertex_6 = geompy.MakeVertex(-190, 
 105, 0)</p>

<p class="whs1">&nbsp;</p>

<p class="whs1">geompy.addToStudy(Vertex_1, 
 &quot;Vertex_1&quot;)</p>

<p class="whs1">geompy.addToStudy(Vertex_2, 
 &quot;Vertex_2&quot;)</p>

<p class="whs1">geompy.addToStudy(Vertex_3, 
 &quot;Vertex_3&quot;)</p>

<p class="whs1">geompy.addToStudy(Vertex_4, 
 &quot;Vertex_4&quot;)</p>

<p class="whs1">geompy.addToStudy(Vertex_5, 
 &quot;Vertex_5&quot;)</p>

<p class="whs1">geompy.addToStudy(Vertex_6, 
 &quot;Vertex_6&quot;)</p>

<p class="whs1">&nbsp;</p>

<p class="whs1">Arc_1 = geompy.MakeArc(Vertex_1, 
 Vertex_6, Vertex_2)</p>

<p class="whs1">Arc_2 = geompy.MakeArc(Vertex_4, 
 Vertex_5, Vertex_3)</p>

<p class="whs1">&nbsp;</p>

<p class="whs1">geompy.addToStudy(Arc_1, 
 &quot;Arc_1&quot;)</p>

<p class="whs1">geompy.addToStudy(Arc_2, 
 &quot;Arc_2&quot;)</p>

<p class="whs1">&nbsp;</p>

<p class="whs2"># Fails</p>

<p class="whs1">Face_3 = geompy.MakeFaceWires([Arc_1, 
 Arc_2], True)</p>

<p class="whs1">if Face_3 is not None:</p>

<p class="whs1">&nbsp;&nbsp;&nbsp;&nbsp;print 
 &quot;Error. Face must not be built from wire with gaps.&quot;</p>

<p class="whs1">&nbsp;</p>

<p class="whs1">Translation_1 = geompy.MakeTranslation(Arc_1, 
 100, 0, 0)</p>

<p class="whs1">geompy.addToStudy(Translation_1, 
 &quot;Translation_1&quot;)</p>

<p class="whs1">&nbsp;</p>

<p class="whs1">Face_3 = geompy.MakeFaceWires([Translation_1, 
 Arc_2], True)</p>

<p class="whs1">geompy.addToStudy(Face_3, 
 &quot;Face_3&quot;)</p>

<p class="whs1">&nbsp;</p>

<p class="whs1">salome.sg.updateObjBrowser(1) 
 </p>

<p class="whs1">&nbsp;</p>

<h3><a name=bookmark2>Creation of a Shell</a></h3>

<p class="whs1"><span style="font-family: 'Lucida Console', monospace;">import 
 geompy</span></p>

<p class="whs1">import salome</p>

<p class="whs1">gg = salome.ImportComponentGUI(&quot;GEOM&quot;)</p>

<p class="whs1">&nbsp;</p>

<p class="whs2">#create vertices</p>

<p class="whs1">p0 &nbsp;&nbsp;= 
 geompy.MakeVertex( 0., &nbsp;0., 
 &nbsp;0.)</p>

<p class="whs1">pxyz = geompy.MakeVertex( 
 5., &nbsp;5., 
 40.)</p>

<p class="whs1">&nbsp;</p>

<p class="whs2"># create sketchers</p>

<p class="whs1">sketcher1 = geompy.MakeSketcher(&quot;Sketcher:F 
 0 0:TT 70 0:TT 70 70:TT 0 70:WW&quot;)</p>

<p class="whs1">sketcher2 = geompy.MakeSketcher(&quot;Sketcher:F 
 20 20:TT 50 20:TT 50 50:TT 20 50:WW&quot;)</p>

<p class="whs1">isPlanarFace = 1</p>

<p class="whs1">&nbsp;</p>

<p class="whs2"># create a face from 
 two wires</p>

<p class="whs1">face = geompy.MakeFaces([sketcher1, 
 sketcher2],isPlanarFace)</p>

<p class="whs1">&nbsp;</p>

<p class="whs2"># create a prism</p>

<p class="whs1">prism = geompy.MakePrism(face, 
 p0, pxyz)</p>

<p class="whs1">&nbsp;</p>

<p class="whs2"># explode the prism into 
 faces</p>

<p class="whs1">prism_faces = geompy.SubShapeAllSorted(prism, 
 geompy.ShapeType[&quot;FACE&quot;])</p>

<p class="whs1">&nbsp;</p>

<p class="whs2"># create a shell from 
 a set of faces</p>

<p class="whs1">shell = geompy.MakeShell([prism_faces[0], 
 prism_faces[2], prism_faces[3],</p>

<p class="whs1">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;prism_faces[7], 
 prism_faces[9]])</p>

<p class="whs1">&nbsp;</p>

<p class="whs2"># add objects in the 
 study</p>

<p class="whs1">id_shell = geompy.addToStudy(shell,&quot;Shell&quot;)</p>

<p class="whs1">&nbsp;</p>

<p class="whs2"># display the shell</p>

<p class="whs1">gg.createAndDisplayGO(id_shell)</p>

<p class="whs1">gg.setDisplayMode(id_shell,1) 
 </p>

<p class="whs1">&nbsp;</p>

<h3><a name=bookmark3>Creation of a Solid</a></h3>

<p class="whs1"><span style="font-family: 'Lucida Console', monospace;">import 
 geompy</span></p>

<p class="whs1">import salome</p>

<p class="whs1">gg = salome.ImportComponentGUI(&quot;GEOM&quot;)</p>

<p class="whs1">&nbsp;</p>

<p class="whs2">#create vertices</p>

<p class="whs1">p0 = geompy.MakeVertex( 
 0., &nbsp;0., 
 &nbsp;0.)</p>

<p class="whs1">pz = geompy.MakeVertex( 
 0., &nbsp;0., 
 40.)</p>

<p class="whs1">&nbsp;</p>

<p class="whs2"># create sketchers</p>

<p class="whs1">sketcher = geompy.MakeSketcher(&quot;Sketcher:F 
 -50 -50:TT 100 -50:R 0:C 50 70:R 0:L 100:WW&quot;)</p>

<p class="whs1">&nbsp;</p>

<p class="whs2"># create faces from two 
 wires</p>

<p class="whs1">face = geompy.MakeFace(sketcher,1)</p>

<p class="whs1">&nbsp;</p>

<p class="whs2"># create a prism</p>

<p class="whs1">prism = geompy.MakePrism(face, 
 p0, pz)</p>

<p class="whs1">&nbsp;</p>

<p class="whs2"># explode the prism into 
 faces</p>

<p class="whs1">prism_faces = geompy.SubShapeAllSorted(prism, 
 geompy.ShapeType[&quot;FACE&quot;])</p>

<p class="whs1">&nbsp;</p>

<p class="whs2"># create a shell from 
 a set of faces</p>

<p class="whs1">shell = geompy.MakeShell([prism_faces[0], 
 prism_faces[1],</p>

<p class="whs1">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;prism_faces[3], 
 prism_faces[4],</p>

<p class="whs1">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;prism_faces[5], 
 prism_faces[2]])</p>

<p class="whs1">&nbsp;</p>

<p class="whs2"># create a solid, bounded 
 by the given shells</p>

<p class="whs1">solid = geompy.MakeSolid([shell])</p>

<p class="whs1">&nbsp;</p>

<p class="whs2"># add objects in the 
 study</p>

<p class="whs1">id_solid = geompy.addToStudy(solid,&quot;Solid&quot;)</p>

<p class="whs1">&nbsp;</p>

<p class="whs2"># display the solid</p>

<p class="whs1">gg.createAndDisplayGO(id_solid)</p>

<p class="whs1">gg.setDisplayMode(id_solid,1) 
 </p>

<p class="whs1">&nbsp;</p>

<h3><a name=bookmark4>Creation of a Compound</a></h3>

<p class="whs1"><span style="font-family: 'Lucida Console', monospace;">import 
 geompy</span></p>

<p class="whs1">import salome</p>

<p class="whs1">&nbsp;</p>

<p class="whs1">gg = salome.ImportComponentGUI(&quot;GEOM&quot;)</p>

<p class="whs1">&nbsp;</p>

<p class="whs2"># create a vertex and 
 a vector</p>

<p class="whs1">p1 = geompy.MakeVertex( 
 &nbsp;-30., &nbsp;-30., 
 &nbsp;50.)</p>

<p class="whs1">p2 = geompy.MakeVertex( 
 &nbsp;-60., &nbsp;-60., 
 &nbsp;30.)</p>

<p class="whs1">p3 = geompy.MakeVertex( 
 &nbsp;-30., &nbsp;-30., 
 &nbsp;10.)</p>

<p class="whs1">&nbsp;</p>

<p class="whs2"># create an arc from 
 three points</p>

<p class="whs1">arc = geompy.MakeArc(p1, 
 p2, p3)</p>

<p class="whs1">ShapeListCompound 
 = []</p>

<p class="whs1">i = 0</p>

<p class="whs1">while i &lt;= 3 :</p>

<p class="whs1">&nbsp;&nbsp;&nbsp;&nbsp;S 
 = geompy.MakeTranslation(arc, i * 50., 0., 0.)</p>

<p class="whs1">&nbsp;&nbsp;&nbsp;&nbsp;ShapeListCompound.append(S)</p>

<p class="whs1">&nbsp;&nbsp;&nbsp;&nbsp;i 
 = i + 1</p>

<p class="whs1">&nbsp;</p>

<p class="whs2"># create a compund of 
 the given shapes</p>

<p class="whs1">compound = geompy.MakeCompound(ShapeListCompound)</p>

<p class="whs1">&nbsp;</p>

<p class="whs2"># add object in the study</p>

<p class="whs1">id_compound = geompy.addToStudy(compound,&quot;Compound&quot;)</p>

<p class="whs1">&nbsp;</p>

<p class="whs2"># display the compound</p>

<p class="whs1">gg.createAndDisplayGO(id_compound) 
 </p>

<script type="text/javascript" language="javascript1.2">
<!--
if (window.writeIntopicBar)
	writeIntopicBar(0);
//-->
</script>
</body>
</html>
