/*!

\page add_point_on_edge_operation_page Add Point on Edge

\n To <b>Add Point on Edge</b> in the <b>Main Menu</b> select
<b>Repair - > Add Point on Edge</b>.

\n This operation splits an edge in two new edges in accordance with the
specified mode (by length or by parameter) and a value specifying the
position of the point on edge (for example val =0.5; mode =
by length). This operation is available in <b>OCC Viewer</b> only.

\n The \b Result will be a \b GEOM_Object.

\n <b>TUI Command:</b> <em>geompy.DivideEdge(Shape, EdgeID, Value,
IsByParameter)</em>
- \em Shape is a shape which contains an edge to be divided
- \em EdgeID is the ID of the edge to be divided, if it is = -1, 
then \em Shape should be an edge itself
- \em Value is a value of parameter on edge or length parameter,
depending on \em IsByParameter.
- \em IsByParameter is a boolean flag, specifying operation mode:
  - \c True: \em Value is treated as a curve parameter [0..1]
  - \c False: \em Value is treated as a length parameter [0..1] 

<b>Arguments:</b> Name + 1 Edge + 1 Value setting the position of
the point according to one of the selected modes.

The difference between "by parameter" and "by length" modes becomes
apparent on the edges with irregular parametrization (for example,
b-splines which usually have irregular density by the length).
For example, value 0.5 "by length" on such edge will produce the point
in the middle of this edge (equidistant from both its ends); the same
0.5 value "by parameter" will result in the point situated closer to
one of the ends (depending on the actual parametrization).

\image html repair8.png

\n <b>Example:</b>

\image html image167.png "The initial edge"

\image html image168.png "The edge split in two segments" 

Our <b>TUI Scripts</b> provide you with useful examples of the use of 
\ref tui_add_point_on_edge "Repairing Operations".

*/
