/*!

\page add_point_on_edge_operation_page Add Point on Edge

\n To <b>Add Point on Edge</b> in the <b>Main Menu</b> select
<b>Repair - > Add Point on Edge</b>.

This operation splits an edge in two or more new edges.
This operation is available in <b>OCC Viewer</b> only.

The \b Result will be a \b GEOM_Object.

\n The location of a new vertex on the selected edge can be defined in two ways:
<ol>
  <li> By specifying the position (ranging from 0.0 to 1.0) by length or by parameter.
    <p>
    <b>TUI Command:</b> <em>geompy.DivideEdge(Shape, EdgeID, Value,
      IsByParameter)</em>
    <ul>
      <li> \em Shape is a shape, which contains an edge to be divided;</li>
      <li>\em EdgeID is the ID of the edge to be divided, if it is = -1,
        then \em Shape should be an edge itself;</li>
      <li> \em Value is a value of parameter on edge or length parameter,
        depending on \em IsByParameter;</li>
      <li> \em IsByParameter is a boolean flag, specifying the operation mode:
        - \c True: \em Value is treated as a curve parameter; [0..1]
        - \c False: \em Value is treated as a length parameter. [0..1] </li>
    </ul>
    \b Arguments: Name + 1 Edge + 1 Value setting the position of
    the point according to the selected mode.

    The difference between "by parameter" and "by length" modes becomes
    apparent on the edges with irregular parametrization (for example,
    b-splines which usually have irregular density by the length).
    For example, value 0.5 "by length" on such edge will produce the point
    in the middle of this edge (equidistant from both its ends); the same
    0.5 value "by parameter" will result in the point situated closer to
    one of the ends (depending on the actual parametrization).

    \image html repair8.png
    \n\n
  </li>
  <li> By selecting several points that will be projected to the selected
    edge to find the location of new vertices.
    <p>
    <b>TUI Command:</b> <em>geompy.DivideEdgeByPoint(Shape, Edge, Points):</em>
    <ul>
      <li> \em Shape is a shape, which contains an edge to be divided;</li>
      <li>\em Edge is an edge to be divided (or its ID, if it is = -1,
        then \em Shape should be an edge itself);</li>
      <li> \em Points is a list of points to be projected to the \a Edge.</li>
    </ul>
    \b Arguments: Name + 1 Edge + 1 or more Points.

    \image html divedgebypoint.png

  </li>
</ol>

\n <b>Example:</b>

\image html image167.png "The initial edge"

\image html image168.png "The edge split in two segments"

Our <b>TUI Scripts</b> provide you with useful examples of the use of
\ref tui_add_point_on_edge "Repairing Operations".

*/
