/*!

\page angle_page Angle

This operation returns the angle in degrees between two lines or linear edges.

\image html angle.png

If both objects are <b>vectors</b>, the angle is computed in accordance with their orientations, otherwise the minimum angle is computed.

\note This dialog supports navigation through the selectable objects (in OCC 3D viewer only):
- Scroll mouse wheel with pressed \em Ctrl key or press \em "S", \em "P" keys when input focus is
in the viewer to navigate between selectable objects.
- Press left mouse button to select an appropriate object to the dialog box.
.
For more details, please refer to the \em "Functionality common for OCC and VTK viewers" chapter
of the GUI module's documentation.

<b>TUI Command:</b> <em>geompy.GetAngle(shape1, shape2),</em> where
Shape1 and Shape2 are shapes between which the angle is computed. 
Another TUI command is <em>geompy.GetAngleRadians(shape1,shape2),</em> 
which returns the value of angle in radians.

See also a \ref tui_angle_page "TUI example".



*/