/*!

\page create_filling_page Filling Surface with Edges

To generate a \b Filling in the <b>Main Menu</b> select <b>New Entity - > Generation  - > Filling</b>

\n To create a curving face using several edges you need to define the
<b>Edges Compound</b>, \b Minimum and <b>Maximum Degree</b>, \b
Tolerance for \b 2D and for \b 3D , the <b>Number of Iterations</b>
and <b>Approximation</b>.
\n The \b Result of the operation will be a GEOM_Object (face).

\n <b>TUI Command:</b> <em>geompy.MakeFilling(Edges, MinDegree,
MaxDegree, Tol2D, Tol3D, NbIter, isApprox)</em>
\n <b>Arguments:</b> Name + 1 Compound of edges + 2 Values (min. and max degree of result BSpline surface) + 2 Values (2D and 3D precision to reach) + 1 Value (number of iterations of approximaion algorithm) + 1 Flag (to select one of algorithms).

\image html filling.png

<b>Example:</b>

\image html filling_compoundsn.png

\image html fillingsn.png

Our <b>TUI Scripts</b> provide you with useful examples of creation of
\ref tui_creation_filling "Complex Geometric Objects".

*/
