/*!

\page create_circle_page Circle

To create a \b Circle in the <b>Main Menu</b> select <b>New Entity - >
Basic - > Circle</b>

\n There are 3 algorithms to create a \b Circle in the 3D space. 
\n The \b Result of each operation will be a GEOM_Object (edge).

\n Firstly, you can define a \b Circle by a <b>Center Point</b>, a \b
Vector giving the circle's normal and a \b Radius.
\n <b>TUI Command:</b> <em>geompy.MakeCircle(Point, Vector,
Radius)</em>
\n <b>Arguments:</b> Name + 1 vertex (for the center) + 1 edge (for
the direction) + Radius.

\note By default it is presumed that the <b>Center Point</b> is located at the  Origin of the global
coordinate system, and the  \b Vector corresponds to OZ axis of the global
coordinate system.

\image html circle1.png

\n Secondly, you can define a \b Circle by three \b Points that lie on it. 
\n <b>TUI Command:</b> <em>geompy.MakeCircleThreePnt(Point1, Point2, Point3)</em>
\n <b>Arguments:</b> Name + 3 points which will form the circle.

\image html circle2.png

\n Finally, you can define a circle by a <b>Center Point</b> and two
\b Points.  
\n <b>TUI Command:</b> <em>geompy.MakeCircleCenter2Pnt(Point1, Point2,
Point3)</em>, where Point1 is the center of the circle, the distance
between point1 and Point2 is the radius of the circle and Point3 helps
to define the plane where the circle lies.
\n <b>Arguments:</b> Name + 3 points.

\image html circle3.png

<b>Example:</b>
\image html circles.png "A circle by vector and radius and a circle by three points"

Our <b>TUI Scripts</b> provide you with useful examples of creation of 
\ref tui_creation_circle "Basic Geometric Objects".

*/
