/*!

\page create_edge_page Edge

To create an \b Edge, in the <b>Main Menu</b> select <b>New Entity >
Build > Edge</b>  

There are two ways to create an edge. In both cases the \b Result
will be a \b GEOM_Object (EDGE). 

1. You can create an \b Edge by specifying two points (\b Point1 and
\b Point2), being the first and the last vertices of the edge.

<b>TUI Command:</b> <em>geompy.MakeEdge(Vertex1, Vertex2)</em><br>
<b>Arguments:</b> Name + 2 vertices (Vertex1 and Vertex2 are
correspondingly the first and the last vertex of the edge).

\image html edge1.png "Create edge by two points"

2. You can create an \b Edge by specifying single wire.

In this mode the following use cases are possible:
- All the edges, forming the wire, lie on the single geometrical curve
(i.e. curve(edge1) == curve(edge2)).
- The edges forming the wire, lie on the analytical curves of the same
type, for example, segments of line, arcs, etc. In this case, an
algorithm checks the geometrical coincidence of these curves using
some tolerance. If the curves are coinciding in terms of given
tolerance, resulting edge is built as on a single curve.
- The edges forming the wire have the same tangency in the connection
points. In this case the curves are interpolated by the single
b-spline curve with the sufficient precision. The resulting edge will
be then built on this curve. 

The case when the edges forming the wire have different tangency in
the connection points (sharp bend) is not processed.

<b>TUI Command:</b> <em>geompy.MakeEdgeWire(Wire, LinearTolerance, AngularTolerance)</em><br>
<b>Arguments:</b> Name + 1 wire + Linear Tolerance + Angular Tolerance
(tolerance are used to check coincidence of the edges' underlying curves).

\image html edge2.png "Create edge from wire"

<b>Example:</b>

\image html edgesn.png "Edge"

Our <b>TUI Scripts</b> provide you with useful examples of creation of 
\ref tui_creation_edge "Advanced Geometric Objects".

*/
