/*!

\page create_face_page Face

To create a \b Face in the <b>Main Menu</b> select <b>New Entity - >
Build - > Face</b>

\n To create a \b Face you need to select a wire, whose elements will
be connected so that the surface of the resulting object was
minimal. Check <b>Try to create a planar face</b> to create a planar
face or nothing if it is impossible.
\n The \b Result will be a \b GEOM_Object (FACE).

\n <b>TUI Command:</b> <em>geompy.MakeFace(Wire, isPlanarWanted)</em>
\n <b>Arguments:</b> Name + 1 wire.

\image html neo-obj4.png

There are some advanced possibilities accessible only via <b>TUI
commands</b>:

<em>geompy.MakeFaceWires(Wires, isPlanarWanted)</em> - Creates a face on the given wires set. The argument is not a single wire, but a list of wires.
<em>geompy.MakeFaces(Wires, isPlanarWanted)</em> is a shortcut to MakeFaceWires(). 

\n <b>Example:</b>

\image html facesn1.png

\image html facesn2.png

\image html facesn3.png

Our <b>TUI Scripts</b> provide you with useful examples of creation of 
\ref tui_creation_face "Advanced Geometric Objects".

*/