/*!

\page create_cylinder_page Cylinder

\n To create a \b Cylinder in the <b>Main Menu</b> select <b>New
Entity - > Primitives - > Cylinder</b>

\n There are 2 algorithms for creation of a \b Cylinder.
\n The \b Result of each operation will be a GEOM_Object (SOLID).

\n Firstly, you can define a \b Cylinder by the <b>Base Point</b> (the central
point of the cylinder base), the \b Vector (the axis of the cylinder),
and its dimensions: the \b Radius and the \b Height. You can optionally specify
the \b Angle to create a portion of cylinder.

\n <b>TUI Command:</b> <em>geompy.MakeCylinder(Point, Axis, Radius, Height)</em>
\n <b>Arguments:</b>  Name + 1 vertex + 1 vector + 2 values
(Dimensions: radius and height).

\n <b>TUI Command:</b> <em>geompy.MakeCylinderA(Point, Axis, Radius, Height, Angle)</em>
\n <b>Arguments:</b>  Name + 1 vertex + 1 vector + 3 values
(Dimensions: radius, height and angle).

\image html cylinder1.png

\n Secondly, you can define a \b Cylinder by the given \b Radius and
\b Height at the origin of coordinate system. The axis of the cylinder
will be collinear to the OZ axis of the coordinate system. 
Similarly to the first constructor, you can optionally specify the \b Angle
to create a portion of cylinder.

\n <b>TUI Command:</b> <em>geompy.MakeCylinderRH(Radius, Height)</em>
\n <b>Arguments:</b> Name + 2 values (Dimensions at origin: radius and
height).

\n <b>TUI Command:</b> <em>geompy.MakeCylinderRHA(Radius, Height, Angle)</em>
\n <b>Arguments:</b>  Name + 3 values
(Dimensions at origin: radius, height and angle).

\image html cylinder2.png

<b>Example:</b>

\image html cylinders.png "Cylinders"

Our <b>TUI Scripts</b> provide you with useful examples of creation of 
\ref tui_creation_cylinder "Primitives".

*/