/*!

\page create_edge_page Edge

To create an \b Edge, in the <b>Main Menu</b> select <b>New Entity >
Build > Edge</b>  

There are three ways to create an edge. In all cases the \b Result
will be a \b GEOM_Object (EDGE). 

Firstly, you can create a linear \b Edge by specifying two points (\b Point1 and
\b Point2), which are the first and the last vertices of the edge.

<b>TUI Command:</b> <em>geompy.MakeEdge(Vertex1, Vertex2)</em><br>
<b>Arguments:</b> Name + 2 vertices (Vertex1 and Vertex2 are
correspondingly the first and the last vertex of the edge).

\image html edge1.png "Create edge by two points"

Secondly, you can create an \b Edge by specifying a single wire.

In this mode the following use cases are possible:
- All edges that form the wire lie on the same geometrical curve
(i.e. curve(edge1) == curve(edge2)).
- The edges that form the wire lie on analytical curves of the same
type, for example, segments of line, arcs, etc. In this case, the
algorithm checks geometrical coincidence of these curves using
a certain tolerance. If the curves are coinciding in terms of the given
tolerance, the resulting edge is built as if on a single curve.
- The edges that form the wire have the same tangency in the connection
points. In this case the curves are interpolated by the single
b-spline curve with sufficient precision. The resulting edge will
be built on this curve. 

The case when the edges that form the wire have different tangency in
the connection points (sharp bend) is not processed.

<b>TUI Command:</b> <em>geompy.MakeEdgeWire(Wire, LinearTolerance, AngularTolerance)</em><br>
<b>Arguments:</b> Name + 1 wire + Linear Tolerance + Angular Tolerance
(tolerance values are used to check coincidence of the underlying curves).

\image html edge2.png "Create edge from wire"

Thirdly, it is possible to build an edge of required \b Length on any existing
\b Edge. 

<b>Start Point</b> parameter is optional:
- if used, it allows selecting any existing point - in such a case the start point
of the new edge will be chosen as start or end point of the selected \b Edge 
whatever is closest to the selected <b>Start Point</b> 
- if it is missed, the start point of the initial edge is used

<b>Length</b> can exceed the length of the initial edge length or be
negative. In this case the existing edge is extrapolated
along its curve (except for bezier and b-spline curves).

<b>TUI Command:</b> <em>geompy.MakeEdgeOnCurveByLength(Edge, Length, StartPoint = None)</em><br>
<b>Arguments:</b> Name + 1 edge + Length + 1 Vertex

\image html edge3.png "Create edge on curve"

<b>Example:</b>

\image html edgesn.png "Edge"

Our <b>TUI Scripts</b> provide you with useful examples of creation of 
\ref tui_creation_edge "Advanced Geometric Objects".

*/
