/*!

\page create_point_page Point

To create a \b Point in the <b>Main Menu</b> select <b>New Entity - >
Basic - > Point</b>

\n There are five algorithms to create a \b Point in the 3D space.
\n Each time the \b Result of the operation will be a GEOM_Object
(vertex).

\n Firstly, we can define a point by setting its X, Y and Z \b Coordinates. 
\n <b>TUI Command:</b> <em>geompy.MakeVertex(X, Y, Z)</em>
\n \b Arguments: Name (Vertex_n by default) + X, Y and Z coordinates of
the point.

\image html point1.png

\n Secondly,  we can define a point by a \b Reference to another point
and the shift of the coordinates of the new point regarding the
coordinates of the old one.
\n <b>TUI Command:</b> <em>geompy.MakeVertexWithRef(Reference, X,Y,Z).</em>
\n <b>Arguments:</b> Name + 1 reference point + 3 coordinates defining
the position of this point regarding the reference one.

\image html point2.png

\n Thirdly, we can define a point by an \b Edge and a \b Parameter
indicating its position on the Edge, ranging from 0.0 to 1.0. For example, 0.5 means that the
point is located in the middle of the edge.
\n <b>TUI Command:</b> <em>geompy.MakeVertexOnCurve(Edge,Parameter,takeOrientationIntoAccount).</em>
\n <b>Arguments:</b> Name + 1 edge  + 1 Parameter defining the
position of the point on the given edge + flag that tells if it is necessary
to take the edge orientation into account.
\image html point3.png

Alternatively, it is possible to define a point by an \b Edge and a \b Length.
The \b Length defines the position of the point on the given edge. It
can exceed the length of the edge or be negative. In this case the edge
is extrapolated along its curve (except for bezier and b-spline
curves). 
The <b>Start Point</b> defines the direction for the length
calculation (if not defined, the first vertex of the 
Edge is used, else the vertex of the Edge, which is closest to the Start Point).
\n <b>TUI Command:</b> <em>geompy.MakeVertexOnCurveByLength(Edge,Length,StartPoint=None).</em>
\n <b>Arguments:</b> Name + 1 edge  + 1 Length  + 1 Point.

\image html point3_3.png

It is also possible to define 3D coordinates of the point
projected on the given edge to produce the resulting point.
\n <b>TUI Command:</b> <em>geompy.MakeVertexOnCurveByCoord(Edge,X,Y,Z).</em>
\n <b>Arguments:</b> Name + 1 edge  + 3 coordinate values of the
projected point.
\image html point3_2.png

\n Fourthly, we can define a point by intersection of two \b Lines or \b Wires (or a Wire and a Line).
If they intersect only once, a point will be created. If there are several intersections, a compound of points will be created.
\n <b>TUI Command:</b> <em>geompy.MakePointOnLinesIntersection(myLine1,myWire1).</em>
\n <b>Arguments:</b> Name + 2 1D objects

\image html point4.png

\n Finally, we can define a point located on a \b Face. 
The position of the point on it can be defined in one of two ways:

- by two <b> Parameters: U </b> and \b V, ranging from 0.0 to 1.0. For example, (0.5; 0.5) means that the point is located in the middle of the face.
\n <b>TUI Command:</b> <em>geompy.MakeVertexOnSurface(myFace,myUParameter,myVParameter).</em>
\n <b>Arguments:</b> Name + 1 face + 2 Parameters defining the position of the point on the given face.

\image html point5.png

- by three coordinates of the point projected on the given face.
\n <b>TUI Command:</b> <em>geompy.MakeVertexOnSurfaceByCoord(myFace,X,Y,Z).</em>
\n <b>Arguments:</b> Name + 1 face  + 3 coordinate values to project point on the given face.

\image html point5_2.png

\note This dialog supports navigation through the selectable objects (in OCC 3D viewer only):
- Scroll mouse wheel with pressed \em Ctrl key or press \em "S", \em "P" keys when input focus is
in the viewer to navigate between selectable objects.
- Press left mouse button to select an appropriate object to the dialog box.
.
For more details, please refer to the \em "Functionality common for OCC and VTK viewers" chapter
of the GUI module's documentation.

<b>Example:</b>

\image html points.png "Points by edge and parameter and by coordinates"

Our <b>TUI Scripts</b> provide you with useful examples of creation of \ref tui_creation_point "Basic Geometric Objects".

*/
