/*!

\page create_sketcher_page 2D Sketcher

The 2D Sketcher allows you to create a profile made of curves of 2 types: line segments and arcs.

<b>Example:</b>

\image html sketch_example.png

To create a <b> 2D Sketch</b>:

<ol>
<li>In the main menu select <em>New Entity -> Basic -> 2D Sketch</em> or click on \image html sketch.png </li>

<li> Select the plane or the planar face on which to create the sketch. By default the sketch is created on the XOY plane of the global coordinate system.
If Local Coordinate systems have been created in the study they appear in the combobox and can be selected as reference coordinate system.</li>

<li> Select a start point. By default the start point of the curve is located at the point of
origin of the reference coordinate system and the curve lies in the
plane XOY.</li>

<li> Create curve portions and click on \b Apply after each step.</li>

<li> Select either \b Close or <b>Sketch Closure</b> if you want to close the profile before closing the window.</li>
</ol>

To create a \b Segment:

<ol>
<li> In the <b>Element Type</b> part of the dialog box select:

\image html line_icon.png </li>

<li> You can define the segment by either it's <b>end point</b> or a \b direction and a length. The direction is defined relatively to the tangent at the last point of the sketch. It can be:

  - Tangent (colinear to the tangent at the last point)
  - Perpendicular
  - Defined by an angle
  - Defined by a vector (Vx, Vy)

</li>

</ol>
  
To create an \b Arc:

<ol>
<li> In the <b>Element Type</b> part of the dialog box select \image html arc_icon.png </li>

<li> You can define the segment by either it's <b>end point</b> or a \b direction a \b radius and an \b angle. </li>

<ul>
  <li>In case of an end point the arc can be built in three different ways:</li>
  <ul>
    <li>From the end point only. The arc is \b tangential to the end of the sketch.</li>
    <li>From the end point and a \b radius. (The radius must be greater than half of the distance between the last point and the end point of the arc).</li>
    <li>From the \b center of the circle and the end point. The constraint on the center is first taken into account.
    The destination point is only used to define the angle of the arc and won't lie on the arc in the general case.</li>
  </ul>
  
  <li>The direction is defined relatively to the tangent at the last point of the sketch. It can be:</li>
  
  <ul>
    <li>Tangent (colinear to the tangent at the last point)</li><
    <li>Perpendicular</li>
    <li>Defined by an angle</li>
    <li>Defined by a vector (Vx, Vy)</li>
  </ul>
</ul>
    
</ol>

For the first segment or arc of the sketch the reference direction is the X direction of the reference coordinate system.

\n The Result of the operation will be a \b Wire.


\n <b>Dialog Box:</b>

\image html sketcher_dlg.png

\n <b>Arguments:</b>
<ol>
<li>Coordinate system (Local or Global CS can be selected)</li>
<li>Element type (segment or arc).</li>
<li>Destination type (point or direction).</li>
<li>Destination point by means of:</li>
<ul>
<li>absolute coordinates X,Y;</li>
<li>relative coordinates DX, DY (with respect to the current point);</li>
<li>selection of an existing point.</li>
</ul>
<li>Destination direction by means of:</li>
<ul>
<li>angle between the new segment and the previous one;</li>
<li>perpendicular to the previous segment (same as previous, but angle
is predefined and is equal to 90 degrees);</li>
<li>tangent to the previous segment;</li>
<li>vector components DX, DY.</li>
</ul>
<li>Parameters of an element (for segment : length or target X or Y coordinate value, for arc : radius, angle or center coordinates).</li>
</ol>

\b Buttons:

<b>"Restore"</b> button orientates the viewer correspondingly to the chosen working plane and fits the scene to show all its objects. 
\n <b>"Sketch Validation"</b> button applies the wire, only red part will be built by "Sketch Validation".
\n <b>"Sketch Closure"</b> will close the Sketch by straight line from last red part and apply it.


\n <b>TUI Command:</b> <em>geompy.MakeSketcherOnPlane(Command, WorkingPlane)</em>
\n This algorithm creates a sketcher (wire or face), following the
textual description, passed through the Command argument. The edges of
the resulting wire or face will be arcs of circles and/or linear
segments.
\n \em Command is a string, defining the sketcher by the coordinates of
points in the current LCS.
\n <em>WorkingPlane</em> can be a Local CS, a plane, or a planar face.


Our <b>TUI Scripts</b> provide you with useful examples of the use of
\ref tui_sketcher_page "Sketcher".

*/
