/*!

\page create_solid_page Solid

\n To create a \b Solid in the <b>Main Menu</b> select <b>New Entity - > Build - >
Solid</b>.

You can create a \b Solid from a list of shells.

The \b Result will be a  \b GEOM_Object (SOLID).

\n <b>TUI Command:</b> <em>geompy.MakeSolid(ListOfShape),</em> where
ListOfShape is a list of shells from which the solid is constructed.
\n <b>Arguments:</b> Name + A closed shell or a list of closed shells.

\image html neo-obj6.png

\n <b>Example:</b>

\image html solidsn.png "Solid"

Our <b>TUI Scripts</b> provide you with useful examples of creation of 
\ref tui_creation_solid "Advanced Geometric Objects".

*/
