/*!

\page create_divideddisk_page DividedDisk

The <b>Divided disk</b> object is a disk divided into \b blocks. It means that it's a shape <b>prepared for hexaedral meshing</b>.

\n Moreover this shape can be used as a basis in an \ref create_extrusion_alongpath_page "Extrusion along a path" operation in order to obtain any <b>tube shape</b> prepared for hexaedral meshing 
(see example below). 

Example:

\image html divided_disk.png

To create a <b> Divided Disk </b> in the <b>Main Menu</b> select <b>New Entity - >
Advanced - > DividedDisk </b>

\n Then there are 2 ways to create a <b> Divided Disk</b> in 3D space. 
\n For both operations : 
Specify the parameters of the DividedDisk object creation in the opened dialog
box and press "Apply" or "Apply & Close" button.
Result of each operation will be a GEOM_Object.

\n First way : by radius and orientation (plane "OXY", "OYZ" or "OZX"). The resulting disk is located at the origin of coordinates

<b>TUI Command:</b> <em>geompy.MakeDividedDisk(Radius, Orientation)</em>

<b>Arguments:</b>
- \b Radius - Radius of the disk
- \b Orientation - Plane on wich the disk will be built

\image html divided_disk_dlg.png

\n Second way : by giving its center, normal and radius.

<b>TUI Command:</b> <em>geompy.MakeDividedDiskPntVecR(Center, Vector,
Radius)</em>

<b>Arguments:</b>
- \b Center - Center of the disk
- \b Vector - Normal to the plane of the disk
- \b Radius - Radius of the disk

\image html divided_disk_PntVecR_dlg.png

Our <b>TUI Scripts</b> provide you with useful examples of creation of
\ref tui_creation_divideddisk "Advanced objects".

*/
