/*!

\page fillet1d_operation_page Fillet 1D

This operation creates fillets on the corners of a <b>Wire with Planar
Edges</b>.
Note, that each couple of edges connected with a vertex, where 1D fillet should be
constructed, have to be in same plane.
\image html fillet1d_2.png

To produce a \b Fillet 1D in the <b>Main Menu</b> select 
<b>Operations - > Transformation - > Fillet 1D</b>

Define the <b>Wire with planar Edges</b> to create a fillet on, select the necessary 
vertexes on this wire in the OCC Viewer and define the \b Radius of the Fillet.

\b Note: This Operation Works for the Wires with <b>Planar Edges</b> Only.

<b>TUI Command:</b> <em>geompy.MakeFillet1D(Shape, R, ListVertexes)</em>
\n <b>Arguments:</b> Name + 1 shape + empty list or several vertexes + 1 value (Fillet radius).

<b>Examples:</b>

\image html fillet1d_1.png

Our <b>TUI Scripts</b> provide you with useful examples of the use of
\ref tui_fillet1d "Transformation Operations".

*/
