/*!

\page fillet_operation_page Fillet 3D

\n To produce a \b Fillet in the <b>Main Menu</b> select 
<b>Operations - > Fillet</b>

\n This operation creates fillets on the edges of a shape.
\n The \b Result will be a \b GEOM_Object.

\n To create fillets on all edges of the given shape, you need to
select the <b>Main Object</b> to create a fillet on and to define the \b Radius of the
Fillet.
\n <b>TUI Command:</b> <em>geompy.MakeFilletAll(Shape, R)</em>
\n <b>Arguments:</b> Name + 1 shape + 1 value (fillet radius).
\n <b>Advanced options</b> \ref preview_anchor "Preview"

\image html fillet1.png

\n To create fillets on the specified edges or faces of the given
shape, you need to define the <b>Main Object</b> to create a fillet
on, select the necessary edges or faces in the OCC Viewer and define
the \b Radius of the Fillet.
\n <b>TUI Command:</b> <em>geompy.MakeFillet(Shape, R, ShapeType, ListShapes)</em>
\n <b>Arguments:</b> Name + 1 shape + one or several edges (or faces)
+ 1 value (Fillet radius).
\n <b>Advanced options</b> \ref preview_anchor "Preview"

\n Alternatively, there is a possibility to create a fillet with a
variable radius.  For this, toggle the lower radio button and define
\b R1 (the radius at the start of the selected edge(s)) and \b R2 
(the radius at the end of the selected edge(s))

\image html fillet2.png

\image html fillet3.png

\n <b>Examples:</b>

\image html fillet_all.png
<center><em>Fillet on all</em></center>

\image html fillet_edge.png
<center><em>Fillet on an edge</em></center>

\image html fillet_prism.png
<center><em>Fillet on a Face</em></center>

Our <b>TUI Scripts</b> provide you with useful examples of the use of
\ref tui_fillet "Transformation Operations".

*/
