/*!

\page fuse_edges_operation_page Fuse Collinear Edges within a Wire

\n To <b>Fuse Collinear Edges within a Wire</b> in the <b>Main Menu</b>
select <b>Repair - > Fuse Collinear Edges within a Wire</b>.
\n This operation removes selected vertices from a given wire in case
if adjacent edges are C1 continuous. The function takes a list of
vertices to suppress as a parameter. If the list is empty, all
vertices in a wire are assumed.

\n <b>Arguments:</b> Name + a wire + a list of vertices (can be empty).

\image html fuse_collinear_edges.png

\n <b>TUI Command:</b> <em>geompy.FuseCollinearEdgesWithinWire(wire, vertices)</em>,
where <em>wire</em> is a wire and <em>vertices</em> is a list of
vertices to be suppressed.

Our <b>TUI Scripts</b> provide you with useful examples of the
\ref tui_fuse_collinear_edges "Fuse Collinear Edges" functionality usage.

*/
