/*!

\page fuse_edges_operation_page Fuse Collinear Edges within a Wire

\n To <b>Fuse Collinear Edges within a Wire</b> in the <b>Main Menu</b>
select <b>Repair - > Fuse Collinear Edges within a Wire</b>.
\n This operation removes the selected vertices from a given wire,
provided that the junction of two adjacent edges is C1 continuous
(i.e. the edges have equal tangents at the junction). 
\n The function takes a list of
vertices to suppress as a parameter. If the list is empty, all
vertices in a wire are taken into account.

\n \b Example:

Wire with 2 colinear edges:
\image html wire_before_fuse.png

Fused wire (only one edge):
\image html fused_wire.png

\n <b>Arguments:</b> Name + a wire + a list of vertices (can be empty).

\image html fuse_collinear_edges.png

\n <b>TUI Command:</b> <em>geompy.FuseCollinearEdgesWithinWire(wire, vertices)</em>,
where <em>wire</em> is a wire and <em>vertices</em> is a list of
vertices to be suppressed.

Our <b>TUI Scripts</b> provide you with useful examples of the
\ref tui_fuse_collinear_edges "Fuse Collinear Edges" functionality usage.

*/
