/*!

\page glue_edges_operation_page Glue Edges

\n To <b>Glue Edges</b> in the <b>Main Menu</b> select <b>Repair - > Glue Edges</b>.

\n This operation glues edges that are coincident with respect to the
given tolerance value.

\n <b>Arguments:</b> Name + Shapes + Tolerance value.
\n <b>Advanced option:</b>
   \ref restore_presentation_parameters_page "Set presentation parameters and sub-shapes from arguments".
\n The \b Result will be a \b GEOM_Object.


\image html glue4.png

\n <b>TUI Command:</b>
<p><em>geompy.MakeGlueEdges( theShapes, theTolerance )</em>,
\n where \em theShapes is a list or compound of shapes to be
glued, and \em theTolerance is a maximum distance between two
edges, which can be considered as coincident.

\n It is also possible to manually select the edges that will be 
glued - select the shape, specify the tolerance and press \b Detect button.

\image html glue5.png

\n \b Geometry module detects the edges where gluing can be
performed and displays a notification.

\image html glue7.png

\n The edges that can be glued are colored in red. It is
possible to select the edges for gluing in the 3D viewer.
The selected edges will be marked in white.

\n <b>TUI Command:</b>
<p><em>geompy.GetGlueEdges( theShapes, theTolerance )</em>,
\n where \em theShape is either a list or compound of shapes to be glued, \em
 theTolerance is a maximum distance between two edges, which can
 be considered as coincident. The \b Result will be a list of \b
 GEOM_Objects (edges), containing one sub-shape per each detected set of
 coincident sub-shapes. For example, if there are two coincident edges
in the selected shapes, the result list contains one of the two coincident edges.

<em>geompy.MakeGlueEdgesByList( theShapes, theTolerance, theEdges )</em>,
\n where \em theShape is a list or compound of shapes to be glued, 
\em theTolerance is a maximum distance between two edges, which can
 be considered as coincident, \em theEdges is a list of
 edges to be glued. 

\n <b>Example:</b>

\image html glue8.png
<center><em>Two boxes with an edge that can be glued</em></center>

Our <b>TUI Scripts</b> provide you with useful examples of the use of
<b>Repairing Operations</b> \ref tui_glue_edges "Glue Edges".

*/
