/*!

\page remove_extra_edges_operation_page Remove Extra Edges

\n To <b>Remove extra edges</b> in the <b>Main Menu</b> select
<b>Repair - > Remove extra edges</b>.
\n This operation removes all seam and degenerated edges from a given
shape. Its main purpose is healing of solids and compounds to obtain
hexahedral solids and compounds of hexahedral solids.
At the same time, it has an option to unite all faces, sharing one
surface. With this option not only hexahedral solids could be obtained.

\n <b>TUI Command:</b> <em>geompy.RemoveExtraEdges(theShape,theOptimumNbFaces)</em>,
there <em>theShape</em> is a compound or a single solid to remove irregular edges from
and <em>theOptimumNbFaces</em> is an integer parameter, that regulates,
whether the faces, sharing common surface, should be united, or not.
\n <b>Arguments:</b> Name + one shape + a flag.
\n <b>Advanced option:</b>
   \ref restore_presentation_parameters_page "Set presentation parameters and subshapes from arguments".

\image html remove_extra_edges.png

\n <b>Example:</b>

\image html remove_extra_edges1.png
<center><em>Shape with extra edges</em></center>

\image html remove_extra_edges2.png
<center><em>Improved shape</em></center>

Our <b>TUI Scripts</b> provide you with useful examples of the
\ref swig_RemoveExtraEdges "Remove Extra Edges" functionality usage.

*/
